### ISSUE TITLE
Hexadecimal

### ISSUE THREAD

**Issue by IanVS** [g45t345rt/minifaker#2]
Hi there!  

After faker.js was deleted, I came across this library and love that it's small and ESM based, and am in the process of migrating to it.  I don't have much usage of faker, but I do find that I'm missing a hexadecimal generator here.  Do you have any recommendations of how to generate a random hex value of a particular length, or is that something you'd consider adding to minifaker?  

Thanks!

**Comment by g45t345rt** [comment]
I've added the missing `hex` function.
https://github.com/g45t345rt/minifaker/blob/a86642862b48d9391d856d51d75e0ff92eeb587f/src/index.ts#L226-L230
