### ISSUE TITLE
Add non-secure nanoid functions

### ISSUE THREAD

**Issue by IanVS** [g45t345rt/minifaker#5]
For my application, I don't need actual secure ids, and nanoid exports a "non-secure" version that is supposedly faster.  Maybe you'd consider supporting those as well?  If no, I can always just add nanoid directly, so not a big deal either way, just thought I'd suggest it.

**Comment by g45t345rt** [comment]
I've added the non-secure version.

You can access it like this
```ts
import { nonsecure } from 'minifaker'
nonsecure.nanoid()
```
