### ISSUE TITLE
Error installing minifaker

### ISSUE THREAD

**Issue by darkadept** [g45t345rt/minifaker#8]
Trying to do a:

`yarn add minifaker`

And I get an error about .yalc.

Looks like this: https://github.com/g45t345rt/minifaker/blame/4d31336b8222c9327679ebb9ec5477280283d286/package.json#L59 might be the culprit.

**Comment by g45t345rt** [comment]
oh it's suppose to be in devDependencies

**Comment by g45t345rt** [comment]
@darkadept should be fixed
